# Limited configuration instead of default_config
# https://github.com/home-assistant/core/tree/dev/homeassistant/components/default_config
automation:
frontend:
history:
logbook:

logger:
  default: info
  logs:
    custom_components.yahoofinance: info

yahoofinance:
  show_trending_icon: true

  #Interval too small - will throw an error
  #scan_interval: 30

  #Update disabled
  #scan_interval: None

  symbols:
    - symbol: GBPUSD=X
    - symbol: IDFCBANK.BO
    - symbol: baba
      target_currency: inr
      scan_interval: 30
    - ^SSMI
    - symbol: EMIM.L
      target_currency: EUR
      scan_interval: 30
    - symbol: AAPL
    - symbol: USDINR=X
      scan_interval: 45
