# Limited configuration instead of default_config
# https://github.com/home-assistant/core/tree/dev/homeassistant/components/default_config
automation:
frontend:
history:
logbook:

logger:
  default: error
  logs:
    custom_components.yahoofinance: debug

yahoofinance:
  show_trending_icon: True
  #scan_interval: 15
  #scan_interval: None
  symbols:
    - symbol: GBPUSD=X
    - symbol: IDFCBANK.BO
    - symbol: baba
      target_currency: inr
    - ^SSMI
    - symbol: EMIM.L
      target_currency: EUR
