default_config:
logger:
  default: error
  logs:
    custom_components.yahoofinance: debug


sensor:
  platform: yahoofinance
  show_trending_icon: True
  symbols:
    - ISTNX
    - GBPUSD=X