#Limited configuration instead of default_config
#https://github.com/home-assistant/core/tree/dev/homeassistant/components/default_config
automation:
frontend:
history:
logbook:

logger:
  default: error
  logs:
    custom_components.yahoofinance: info

yahoofinance:
  show_trending_icon: True
  decimal_places: 1
  symbols:
    - GBPUSD=X
    - IDFCBANK.BO
    - baba
    - ^SSMI